---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Get Join command
  shell:
    cmd: kubeadm token create --ttl 1m --print-join-command
  register: join_command
  delegate_to: "{{ master_node }}"

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    {{ join_command.stdout }}
  notify:
    - Recreate kube-dns
