---
- name: Install common packages for k8s-cluster
  hosts: common
  remote_user: ubuntu
  become: yes
  roles:
    - common

- name: Configure docker and kubernetes
  hosts: common
  remote_user: ubuntu
  become: yes
  roles:
    - {role: kubernetes/common}

- name: Configure kubernetes master
  hosts: master
  remote_user: ubuntu
  become: yes
  environment:
    K8S_AUTH_KUBECONFIG: "{{kubeadmin_config}}"
  roles:
    - {role: kubernetes/master}
    - {role: kubernetes/addons/cni}

- name: Configure kubernetes nodes
  hosts: node
  remote_user: ubuntu
  become: yes
  roles:
    - kubernetes/node
